name: copy
on: [push, pull_request]

jobs:
  test:
    name: copy
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v1
      - name: Python file
        run: os.py
        shell: python


